### ISSUE TITLE
Conversion

### ISSUE THREAD

**Issue by zBoringDrop** [Beelzebu/Coins#10]
Hi, how i can convert the flatfile of gmoney(bukkit plugin) to this?

**Comment by Beelzebu** [comment]
Hi, if you're using gmoney linked to vault you must enable vault in coins and run the command `/vault-convert <old economy> Coins> `

**Comment by zBoringDrop** [comment]
And i must have gmoney.jar + folder and also Coins.jar + folder to do this?

**Comment by Beelzebu** [comment]
Yes, you must have the two plugins running on the server to do the conversion, after that you can remove gmoney

**Comment by Beelzebu** [comment]
Can I close this? @zBoringDrop

**Comment by zBoringDrop** [comment]
Oh sorry, i forget, but Yes. Thanks ^^
You can close
